### ISSUE TITLE
`netbios name` and `mdns name` are templated to a single line

### ISSUE THREAD

**Issue by agross** [vladgh/ansible-collection-vladgh-samba#115]
With the default vars (`samba_netbios_name` and `samba_mdns_name` undefined) this is the templated `/etc/samba/smb.conf` on my server:

```conf
#
# Ansible managed
#

[global]
  # Server information
  netbios name = finn  mdns name = netbios
...
```

The issue is that `netbios name` and `mdns name` are placed on a single line.

```sh
$ testparm -s
Load smb config files from /etc/samba/smb.conf
Loaded services file OK.
Weak crypto is allowed by GnuTLS (e.g. NTLM as a compatibility fallback)

WARNING: The 'netbios name' is too long (max. 15 chars).

Server role: ROLE_STANDALONE

# Global parameters
[global]
        ...
        netbios name = FINN MDNS NAME = NETBIOS
```

https://github.com/vladgh/ansible-collection-vladgh-samba/blob/52eb8275b94cb17268a1b020a357a387d02c9a5c/roles/server/templates/smb.conf.j2#L5-L6

I thought that [this role's use of the `template` module](https://github.com/vladgh/ansible-collection-vladgh-samba/blob/52eb8275b94cb17268a1b020a357a387d02c9a5c/roles/server/tasks/main.yml#L80-L88) might have enabled `lstrip_blocks` or `trim_blocks` but it appears not to be the case. 

**A workaround is to place an extra line between the two lines linked above.**

```sh
$ ansible --version
ansible [core 2.15.5]
  config file = None
  configured module search path = ['/Users/agross/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.5.0_1/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/agross/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] (/opt/homebrew/Cellar/ansible/8.5.0_1/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

**Comment by vladgh** [comment]
Thanks for catching that. I created a pull request to fix it, and by adding a `+` at the end of the block, the new lines should be preserved.

**Comment by agross** [comment]
Confirmed to be working now. Thanks!
