### ISSUE TITLE
Feature request: samba_disable_netbios

### ISSUE THREAD

**Issue by tdltdc** [vladgh/ansible-collection-vladgh-samba#119]
The Samba server I'm deploying is not used by Windows clients. Therefore, there is no need for NetBIOS to be enabled. Disabling it reduced the server's attack surface.

There is a parameter in Samba already for disabling NetBIOS (`disable netbios = Yes`). However, simply putting this in a global include file conflicts with this role, because this role always tries to enable the `nmbd` service.

I'm willing to take a shot at creating a pull request for adding a `samba_disable_netbios` parameter to this collection, but would first like to know whether you believe this would be a useful addition @vladgh.

**Comment by vladgh** [comment]
This is a great idea, and a PR would be appreciated. Thanks!

**Comment by gparent** [comment]
I am hitting the exact issue you mentioned with the `nmbd` service restarting after using global include, so you're definitely not the only one.

**Comment by tdltdc** [comment]
I took a crack at a pull request: https://github.com/vladgh/ansible-collection-vladgh-samba/pull/120

**Comment by vladgh** [comment]
Thank you for your work and time!

**Comment by tdltdc** [comment]
> Thank you for your work and time!

My pleasure. Thanks for the quick and helpful review!
