### ISSUE TITLE
Check mode fails with message: "Input version value cannot be empty"

### ISSUE THREAD

**Issue by gparent** [vladgh/ansible-collection-vladgh-samba#121]
When running this role in check mode (`--check`), the role fails:

```
fatal: [test.example.org]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: Input version value cannot be empty"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFilterError: Input version value cannot be empty
```

Assuming the version check is without side effects*, we can fix this by adding `check_mode: false` to the relevant task so that the information is available to the template that uses it.

*: I really don't know, but can only assume so and that otherwise would be a bug to raise to Samba developers.

**Comment by jdavcs** [comment]
This is still the case:
```
The conditional check 'postgresql_version is version('9.3', '>=')' failed. The error was: Input version value cannot be empty
```
