### ISSUE TITLE
samba user password changes are not recognized

### ISSUE THREAD

**Issue by dessert1** [vladgh/ansible-collection-vladgh-samba#131]
[The “Create Samba users if they don't exist yet” task](https://github.com/vladgh/ansible-collection-vladgh-samba/blob/ac7a82e8998030306dba9456908776b7385c4205/roles/server/tasks/main.yml#L156C9-L156C51) only configures user passwords initially. Because of that, a samba user password change is not propagated by the role.

**Comment by vladgh** [comment]
I would love to add this, but I don't see an idempotent way to change the password. When running `smbpasswd` it will only output `Added user xxxx`, but nothing when changing the password. And I wouldn't want for this command to run every time we run the ansible playbook.

I will close this for now, but if anyone figures this out, I would gladly add it.
