### ISSUE TITLE
Using 'false' as value for share option doesn't work

### ISSUE THREAD

**Issue by Yemtex** [vladgh/ansible-collection-vladgh-samba#155]
### read only

`read_only: false` should generate `read only = no`, but due to the way the condition is written in the smb.conf jinja template, the condition will always be false and never generate the line as a result.

My current workaround, using `writeable: true` or `read_only: 'no'` instead.

### guest ok

The same applies to `guest_ok: false`
Additionally it should be noted that according to the [smb.conf documentation](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#GUESTOK) the default value for `guest ok` should be `no`.
Furthermore, `public` is a synonym for `guest ok`. By default, `public` is set to `no` without a condition, which could also lead to problems.

No workaround necessary. Using `guest_ok: false` is currently not necessary, due to `public`

### Possible solutions

- If you mention this in the documentation, I think it will help a lot of people. Instead of using boolean values, you should stick with `no` and `yes`.
- Removing `and <var>` at the end of every condition

**Comment by Yemtex** [comment]
Okey, for whatever reason, using `read_only: 'no'` does not work.

**Comment by vladgh** [comment]
Thank you for bringing this up. See my previous comment here: https://github.com/vladgh/ansible-collection-vladgh-samba/issues/127#issuecomment-2103124728 That should fix this issue. I pull request is in the works to address this.
