### ISSUE TITLE
Dependency for fedora linux

### ISSUE THREAD

**Issue by pablodav** [vladgh/ansible-collection-vladgh-samba#38]
Testing it on fedora I found this var should be changed:

from:
```yaml
samba_selinux_packages:
  - libsemanage-python
```

to:
```yaml
samba_selinux_packages:
  - python3-libsemanage
```

from vars/os_RedHat.yml to a new similar file for fedora or something similar based on version >=?

**Comment by vladgh** [comment]
Which Fedora version did you test?

**Comment by pablodav** [comment]
I'm running Fedora 37, but it is same since Fedora 35.
Same for Centos8 and 9.

https://pkgs.org/search/?q=python3-libsemanage

**Comment by vladgh** [comment]
The new version that is currently being published should fix your issue. Let me know if anything else comes up in your tests.
