### ISSUE TITLE
smb.conf.j2 template does not properly compare Samba version

### ISSUE THREAD

**Issue by economycomfort** [vladgh/ansible-collection-vladgh-samba#56]
Line 75 of `roles/server/templates/smb.conf.j2` attempts to compare string values of the running Samba version.  Unfortunately this comparison doesn't operate as intended, causing CVE mitigation to occur in situations it shouldn't.  The side effect of the `nt pipe support = no` setting causes MacOS clients, and possibly others, to not be able to browse shares, only mount them directly (which can be quite disruptive and confusing!)

Replacing the line:
`{% if samba_mitigate_cve_2017_7494 and samba_version.stdout >= "3.5.0" and samba_version.stdout < "4.6.4" %}`

With:
`{% if samba_mitigate_cve_2017_7494 and samba_version.stdout is version('3.5.0', '>=') and samba_version.stdout is version('4.6.4', '<') %}`

Corrects the issue and properly computes the Samba version.  It's a simple change, but I have a PR ready if you'd like

**Comment by vladgh** [comment]
Good catch. I agree the version() function is much better for this. A PR would be appreciated. Thanks.
