### ISSUE TITLE
Option to disable creation and management of directories

### ISSUE THREAD

**Issue by andrewradke** [vladgh/ansible-collection-vladgh-samba#99]
We have a "live" samba server and also our backup server.

The backup server has ZFS copies of the live server mounted read-only with ZFS snapshots exposed via the vfs shadow_copy2

We need to be able to tell Ansible not to create or manage the directories on the backup server as it always fails due to the read-only nature of the filesystem.

Our old Puppet system that we are replacing had a share option of `manage_directory` that when set to false would skip any creation or permission checks.

Testing something similar with your Ansible role I've added a couple of things to `roles/server/tasks/main.yml`

Under Create Samba shares root directory (for the main samba_shares_root setting):
`   when: (samba_shares|length > 0) and
         (samba_manage_directories is undefined or samba_manage_directories != false)`

And under Create share directories:
`  when: item.manage_directory is undefined or item.manage_directory != false`

This appears to work as I'd hope. What is your opinion of this?

**Comment by vladgh** [comment]
Yes, I think it's a good idea to have that option available. It should default to `true` though (create the directories). Would you be willing to open a pull request?

**Comment by andrewradke** [comment]
I can open a pull request. Never actually done it but there's always a first time.

I in effect had it default to true by saying to create if undefined or false if it is defined. Happy to do it differently if there is a better Ansible way.

**Comment by vladgh** [comment]
Just ensure the variable is named like `samba_manage_directories`, and it has a default value of `true` in `defaults/main.yml`. 
It would look like:
```yml
  when: >
        ( samba_shares is defined and samba_shares | length > 0 ) and
        ( samba_manage_directories is defined and samba_manage_directories )
```

Thanks!

**Comment by andrewradke** [comment]
I believe I've updated the pull request. Let me know if it's come through. I've got a few other small things I'd like to suggest but I'd like to know I've got this working first.
